### ISSUE TITLE
tgrepost checklist

### ISSUE THREAD

**Issue by parkanaur** [parkanaur/dansstuff-site#3]
- [x] refactor CSS so that they are shared across all blueprints
- [x] add account creation page ("/tgrepost/signup", GET/POST)
- [ ] add a group submit form ("/tgrepost/create", GET/POST)
- [x] add a login page ("/tgrepost/login", GET/POST)
- [ ] add info edit page ("/tgrepost/public{}", GET/POST)
- [x] create DB schema for tgrepost (SQLite/SQLAlchemy, models)
- [x] bind DB to project
- [ ] integrate repost BL into project
- [ ] add instructions page ("/tgrepost/howto", GET)
- [x] add groups list page ("/tgrepost/groups", GET)
